name: Build and run tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-distutils gcc make
      - run: python3 configure
      - run: make
      - run: make test
